name: 2D API Auto Run Cron
on:
  schedule:
    # ၁။ မြန်မာစံတော်ချိန် မနက် ၀၉:၀၀ မှ ၀၉:၀၃ ထိ (၁ မိနစ်တစ်ကြိမ်) - စနေ၊ တနင်္ဂနွေ မပါ
    - cron: '0-3 2 * * 1-5'
    # ၂။ မြန်မာစံတော်ချိန် နေ့လယ် ၁၂:၀၀ မှ ၁၂:၀၃ ထိ (၁ မိနစ်တစ်ကြိမ်) - စနေ၊ တနင်္ဂနွေ မပါ
    - cron: '0-3 5 * * 1-5'
    # ၃။ မြန်မာစံတော်ချိန် ညနေ ၁၆:၂၉ မှ ၁၆:၃၂ ထိ (၁ မိနစ်တစ်ကြိမ်) - စနေ၊ တနင်္ဂနွေ မပါ
    - cron: '29-32 9 * * 1-5'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger 2D API
        run: |
          curl -s "https://2d-live-api.vercel.app/"
          
